replicaCount: 2

image:
  repository: 030569356836.dkr.ecr.eu-west-1.amazonaws.com/bmw-app
  pullPolicy: IfNotPresent
  tag: "0.1"

service:
  type: ClusterIP
  port: 80 # Can terminate SSL on ALB, and only worry about port 80 inside EKS.
  targetPort: 8000

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /   # or /health
  hosts:
    - host: mybmw.pieterza.com   # Use an /etc/host entry to the alb IP.
      paths:
       - path: /
         pathType: Prefix
